### ISSUE TITLE
Fix integration tests in monorepo

### ISSUE THREAD

**Issue by siepra** [ZbayApp/monorepo#1]
Some problems occurred after migrating integration tests from nectar to separate package. They're probably related to malformed imports

**Comment by siepra** [comment]
`  ● registrar is offline, user tries to join, then registrar goes online › owner goes offline

    TypeError: Cannot read property 'values' of null

      at KeyValueIndex.updateIndex (../../waggle/node_modules/orbit-db-kvstore/src/KeyValueIndex.js:13:11)
      at KeyValueStore._updateIndex (../../waggle/node_modules/orbit-db-store/src/Store.js:411:23)
      at KeyValueStore.addOperation (../../waggle/node_modules/orbit-db-store/src/Store.js:437:20)
      at run (../../waggle/node_modules/p-queue/dist/index.js:163:29)`
