### ISSUE TITLE
Sending message too early causes "TypeError: Cannot read property 'storage' of undefined`"

### ISSUE THREAD

**Issue by EmiM** [ZbayApp/monorepo#14]
I noticed that we sometimes get this error while running e2e tests (both locally and on CI).
It looks like we are trying to send a message before community is fully initialized.

```
e2e-tests: 2021-12-22T12:45:25.682Z testcafe:browser-provider-electron:spawn:stderr 2021-12-22T12:45:25.682Z waggle:conn Spawned Tor
e2e-tests: 2021-12-22T12:45:25.729Z testcafe:browser-provider-electron:spawn:stderr 2021-12-22T12:45:25.721Z waggle:socket websocket connected
e2e-tests: 2021-12-22T12:45:38.091Z testcafe:browser-provider-electron:spawn:stderr 2021-12-22T12:45:38.091Z waggle:socket Creating network for community B8E95677A19A889CA5E3F591D8690BF0
Notice: s: 2021-12-22T12:45:38.126Z testcafe:browser-provider-electron:spawn:stderr 2021-12-22T12:45:38.115Z waggle:tor Dec 22 12:45:38.000 [notice] New control connection opened from 127.0.0.1.
Notice: s: 2021-12-22T12:45:38.202Z testcafe:browser-provider-electron:spawn:stderr 2021-12-22T12:45:38.202Z waggle:tor Dec 22 12:45:38.000 [notice] New control connection opened from 127.0.0.1.
e2e-tests: 2021-12-22T12:45:45.757Z testcafe:browser-provider-electron:spawn:stderr 2021-12-22T12:45:45.757Z waggle:conn Created network for peer QmTZ588JkYAAzGy6AH14uw3crryW5Xuon6Emdjm9AdLDGy. Address: tpz72ybydkwzu5ccy3tpaebed4bt63j77yvjy5q7mikif3zfi7xrq6id.onion
e2e-tests: 2021-12-22T12:45:45.835Z testcafe:browser-provider-electron:spawn:stderr 2021-12-22T12:45:45.835Z waggle:socket Registering owner certificate (B8E95677A19A889CA5E3F591D8690BF0)
e2e-tests: 2021-12-22T12:45:45.928Z testcafe:browser-provider-electron:spawn:stderr 2021-12-22T12:45:45.928Z waggle:socket Launching community B8E95677A19A889CA5E3F591D8690BF0 for QmTZ588JkYAAzGy6AH14uw3crryW5Xuon6Emdjm9AdLDGy
e2e-tests: 2021-12-22T12:45:45.931Z testcafe:browser-provider-electron:spawn:stderr 2021-12-22T12:45:45.931Z waggle:communities Spawning hidden service for community B8E95677A19A889CA5E3F591D8690BF0, peer: QmTZ588JkYAAzGy6AH14uw3crryW5Xuon6Emdjm9AdLDGy
Notice: s: 2021-12-22T12:45:45.938Z testcafe:browser-provider-electron:spawn:stderr 2021-12-22T12:45:45.937Z waggle:tor Dec 22 12:45:45.000 [notice] New control connection opened from 127.0.0.1.
e2e-tests: 2021-12-22T12:45:45.999Z testcafe:browser-provider-electron:spawn:stderr 2021-12-22T12:45:45.995Z waggle:communities Launching community B8E95677A19A889CA5E3F591D8690BF0, peer: QmTZ588JkYAAzGy6AH14uw3crryW5Xuon6Emdjm9AdLDGy
e2e-tests: 2021-12-22T12:45:46.006Z testcafe:browser-provider-electron:spawn:stderr 2021-12-22T12:45:46.006Z waggle:communities Initializing storage for peer QmTZ588JkYAAzGy6AH14uw3crryW5Xuon6Emdjm9AdLDGy...
e2e-tests: 2021-12-22T12:45:46.007Z testcafe:browser-provider-electron:spawn:stderr 2021-12-22T12:45:46.006Z waggle:conn Initializing libp2p for QmTZ588JkYAAzGy6AH14uw3crryW5Xuon6Emdjm9AdLDGy
e2e-tests: 2021-12-22T12:45:46.019Z testcafe:browser-provider-electron:spawn:stderr 2021-12-22T12:45:46.019Z waggle:conn Initialized libp2p for peer QmTZ588JkYAAzGy6AH14uw3crryW5Xuon6Emdjm9AdLDGy
e2e-tests: 2021-12-22T12:45:46.020Z testcafe:browser-provider-electron:spawn:stderr 2021-12-22T12:45:46.019Z waggle:conn Creating storage for community: B8E95677A19A889CA5E3F591D8690BF0
e2e-tests: 2021-12-22T12:45:46.019Z waggle:db STORAGE: Entered init
e2e-tests: 2021-12-22T12:45:46.020Z testcafe:browser-provider-electron:spawn:stderr 2021-12-22T12:45:46.020Z waggle:db Initializing IPFS
e2e-tests: 2021-12-22T12:45:47.136Z testcafe:browser-provider-electron:spawn:stdout to get started, enter:
e2e-tests: 2021-12-22T12:45:47.136Z testcafe:browser-provider-electron:spawn:stdout 	jsipfs cat /ipfs/QmRaaUwTNfwgFZpeUy8qrZwrp2dY4kCKmmB5xEqvH3vtD1/readme
e2e-tests: 2021-12-22T12:45:47.162Z testcafe:browser-provider-electron:spawn:stderr 2021-12-22T12:45:47.161Z waggle:communities:err No available Storage for peer QmTZ588JkYAAzGy6AH14uw3crryW5Xuon6Emdjm9AdLDGy
e2e-tests: 2021-12-22T12:45:47.164Z testcafe:browser-provider-electron:spawn:stderr TypeError: Cannot read property 'storage' of undefined
e2e-tests:     at CommunitiesManager.getStorage (/home/runner/work/monorepo/monorepo/packages/waggle/lib/communities/manager.js:116:45)
e2e-tests:     at IOProxy.getStorage (/home/runner/work/monorepo/monorepo/packages/waggle/lib/socket/IOProxy.js:141:37)
e2e-tests:     at IOProxy.<anonymous> (/home/runner/work/monorepo/monorepo/packages/waggle/lib/socket/IOProxy.js:53:24)
e2e-tests:     at Generator.next (<anonymous>)
e2e-tests:     at /home/runner/work/monorepo/monorepo/packages/waggle/lib/socket/IOProxy.js:8:71
e2e-tests:     at new Promise (<anonymous>)
e2e-tests:     at __awaiter (/home/runner/work/monorepo/monorepo/packages/waggle/lib/socket/IOProxy.js:4:12)
e2e-tests:     at IOProxy.sendMessage (/home/runner/work/monorepo/monorepo/packages/waggle/lib/socket/IOProxy.js:42:72)
e2e-tests:     at /home/runner/work/monorepo/monorepo/packages/waggle/lib/socket/listeners/connection.js:29:27
e2e-tests:     at Generator.next (<anonymous>)
e2e-tests: 2021-12-22T12:45:47.288Z testcafe:browser-provider-electron:spawn:stderr 2021-12-22T12:45:47.274Z waggle:db 1/6
e2e-tests: 2021-12-22T12:45:47.274Z waggle:db createDbForChannels init
e2e-tests: 2021-12-22T12:45:47.373Z testcafe:browser-provider-electron:spawn:stderr 2021-12-22T12:45:47.324Z waggle:db ALL CHANNELS COUNT: 0
e2e-tests: 2021-12-22T12:45:47.325Z waggle:db ALL CHANNELS COUNT: []
e2e-tests: 2021-12-22T12:45:47.325Z waggle:db STORAGE: Finished createDbForChannels
e2e-tests: 2021-12-22T12:45:47.325Z waggle:db 2/6
e2e-tests: 2021-12-22T12:45:47.325Z waggle:db createDbForCertificates init
e2e-tests: 2021-12-22T12:45:47.337Z waggle:db Loaded certificates to memory
e2e-tests: 2021-12-22T12:45:47.337Z waggle:socket Sending back 0 certificates
e2e-tests: 2021-12-22T12:45:47.337Z waggle:db ALL Certificates COUNT: 0
e2e-tests: 2021-12-22T12:45:47.337Z waggle:db ALL Certificates: []
```

**Comment by EmiM** [comment]
I am able to reproduce it manually

**Comment by EmiM** [comment]
https://github.com/ZbayApp/monorepo/pull/138/files
