### ISSUE TITLE
Electron updater throws error on Linux

### ISSUE THREAD

**Issue by EmiM** [ZbayApp/monorepo#176]
```
Error: Error: sha512 checksum mismatch, expected LJDTvCbEBJyxD5elDsQASf1IibaERUtyh3iSm5fhorQ9A7hwd7dShpxqk1Z/uk1/UpH0WU/xdPKJ5mifXkxbdg==, got jdFPyx5H+4BJTp5xHyMJ/D+9j1Ru5PN/ys0wsYJjl5Oj/mStcDAe6LlbX3svB5CWlSV0szUXOOkxb6I0Y9KEzw==
    at newError (/tmp/.mount_Quiet-NuiJG0/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/src/index.ts:29:17)
    at DigestTransform.validate (/tmp/.mount_Quiet-NuiJG0/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/src/httpExecutor.ts:378:13)
    at DigestTransform._flush (/tmp/.mount_Quiet-NuiJG0/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/src/httpExecutor.ts:361:14)
    at DigestTransform.prefinish (internal/streams/transform.js:147:10)
    at DigestTransform.emit (events.js:315:20)
    at prefinish (internal/streams/writable.js:630:14)
    at finishMaybe (internal/streams/writable.js:638:5)
    at DigestTransform.Writable.end (internal/streams/writable.js:582:5)
    at IncomingMessage.onend (internal/streams/readable.js:684:10)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:315:20)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
From previous event:
    at ElectronHttpExecutor.download (/tmp/.mount_Quiet-NuiJG0/resources/app.asar/node_modules/electron-updater/src/electronHttpExecutor.ts:23:73)
    at Object.<anonymous> (/tmp/.mount_Quiet-NuiJG0/resources/app.asar/node_modules/electron-updater/src/AppImageUpdater.ts:62:35)
    at Generator.throw (<anonymous>)
From previous event:
    at Object.task (/tmp/.mount_Quiet-NuiJG0/resources/app.asar/node_modules/electron-updater/src/AppImageUpdater.ts:37:11)
    at /tmp/.mount_Quiet-NuiJG0/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:610:25
From previous event:
    at AppImageUpdater.executeDownload (/tmp/.mount_Quiet-NuiJG0/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:545:68)
    at AppImageUpdater.executeDownload (/tmp/.mount_Quiet-NuiJG0/resources/app.asar/node_modules/electron-updater/src/BaseUpdater.ts:27:18)
    at AppImageUpdater.doDownloadUpdate (/tmp/.mount_Quiet-NuiJG0/resources/app.asar/node_modules/electron-updater/src/AppImageUpdater.ts:33:17)
    at AppImageUpdater.downloadUpdate (/tmp/.mount_Quiet-NuiJG0/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:420:19)
    at /tmp/.mount_Quiet-NuiJG0/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:383:49
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/tmp/.mount_Quiet-NuiJG0/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:360:34)
    at AppImageUpdater.checkForUpdates (/tmp/.mount_Quiet-NuiJG0/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:220:35)
    at /tmp/.mount_Quiet-NuiJG0/resources/app.asar/dist/main/main.js:224:46
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_Quiet-NuiJG0/resources/app.asar/dist/main/main.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by vinkabuki** [comment]
https://stackoverflow.com/questions/46407362/checksum-mismatch-after-code-sign-electron-builder-updater
electron-userland/electron-builder#3913 (comment)

**Comment by vinkabuki** [comment]
It happens because we have setEnvs scripts that unpacks build, set library and pack it.

**Comment by vinkabuki** [comment]
Blocked at this moment. I've asked for help on electron-builder chat, they replied, but we are not using the current version of electron builder, which has new API, We must first bump electron version

**Comment by EmiM** [comment]
https://github.com/ZbayApp/monorepo/pull/221

**Comment by kingalg** [comment]
It's working in 0.4.7-alpha.1.
