### ISSUE TITLE
Application crashes when tor fails to spawn > 3 times ("Unable to write state to file")

### ISSUE THREAD

**Issue by EmiM** [ZbayApp/monorepo#273]
OS: 
Quiet app version: 0.3.0-alpha.7

There are two problems:
1. Tor sometimes fails to start with error: `Unable to write state to file "(...)/Quiet/TorDataDirectory/state"; will try again later`
2. We don't handle failing Tor very nicely - user sees the javascript error.

```
olgadegtiarova@Olgas-MacBook-Air-2 Applications % DEBUG=waggle* /Applications/Quiet.app/Contents/MacOS/Quiet
 waggle:socket Data server running on port 52599 +0ms
 waggle:conn Creating https proxy agent: 52596 +0ms
 waggle:conn Initialized socket listeners +1ms
 waggle:tor Initializing tor... +0ms
 waggle:tor Feb 24 11:33:28.024 [notice] Tor 0.4.6.9 (git-ea2ada6d1459f829) running on Darwin with Libevent 2.1.11-stable, OpenSSL 1.1.1m, Zlib 1.2.11, Liblzma N/A, Libzstd N/A and Unknown N/A as libc.
 waggle:tor Feb 24 11:33:28.024 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
 waggle:tor  +46ms
 waggle:tor Feb 24 11:33:28.025 [notice] Configuration file "/var/tmp/dist/tor/etc/tor/torrc" not present, using reasonable defaults.
 waggle:tor  +1ms
 waggle:tor Feb 24 11:33:28.027 [notice] Opening Socks listener on 127.0.0.1:52597
 waggle:tor  +2ms
 waggle:tor Feb 24 11:33:28.028 [notice] Opened Socks listener connection (ready) on 127.0.0.1:52597
 waggle:tor Feb 24 11:33:28.028 [notice] Opening HTTP tunnel listener on 127.0.0.1:52596
 waggle:tor Feb 24 11:33:28.028 [notice] Opened HTTP tunnel listener connection (ready) on 127.0.0.1:52596
 waggle:tor Feb 24 11:33:28.028 [notice] Opening Control listener on 127.0.0.1:52595
 waggle:tor Feb 24 11:33:28.028 [notice] Opened Control listener connection (ready) on 127.0.0.1:52595
 waggle:tor  +1ms
 waggle:tor Feb 24 11:33:28.000 [notice] Bootstrapped 0% (starting): Starting
 waggle:tor Feb 24 11:33:28.000 [notice] Starting with guard context "default"
 waggle:tor  +35ms
 waggle:tor Feb 24 11:34:08.000 [notice] Catching signal TERM, exiting cleanly.
 waggle:tor  +40s
 waggle:tor Feb 24 11:34:08.049 [notice] Tor 0.4.6.9 (git-ea2ada6d1459f829) running on Darwin with Libevent 2.1.11-stable, OpenSSL 1.1.1m, Zlib 1.2.11, Liblzma N/A, Libzstd N/A and Unknown N/A as libc.
 waggle:tor Feb 24 11:34:08.049 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
 waggle:tor Feb 24 11:34:08.049 [notice] Configuration file "/var/tmp/dist/tor/etc/tor/torrc" not present, using reasonable defaults.
 waggle:tor  +12ms
 waggle:tor Feb 24 11:34:08.051 [notice] Opening Socks listener on 127.0.0.1:52597
 waggle:tor  +2ms
 waggle:tor Feb 24 11:34:08.051 [notice] Opened Socks listener connection (ready) on 127.0.0.1:52597
 waggle:tor Feb 24 11:34:08.051 [notice] Opening HTTP tunnel listener on 127.0.0.1:52596
 waggle:tor Feb 24 11:34:08.051 [notice] Opened HTTP tunnel listener connection (ready) on 127.0.0.1:52596
 waggle:tor Feb 24 11:34:08.051 [notice] Opening Control listener on 127.0.0.1:52595
 waggle:tor Feb 24 11:34:08.051 [notice] Opened Control listener connection (ready) on 127.0.0.1:52595
 waggle:tor  +1ms
 waggle:tor Feb 24 11:34:08.000 [notice] Bootstrapped 0% (starting): Starting
 waggle:tor  +37ms
 waggle:tor Feb 24 11:34:08.000 [notice] Starting with guard context "default"
 waggle:tor  +1ms
 waggle:tor Feb 24 11:34:18.000 [notice] Bootstrapped 5% (conn): Connecting to a relay
 waggle:tor  +10s
 waggle:tor Feb 24 11:34:19.000 [notice] Bootstrapped 10% (conn_done): Connected to a relay
 waggle:tor  +2s
 waggle:tor Feb 24 11:34:22.000 [notice] Bootstrapped 14% (handshake): Handshaking with a relay
 waggle:tor  +3s
 waggle:tor Feb 24 11:34:48.000 [notice] Catching signal TERM, exiting cleanly.
 waggle:tor Feb 24 11:34:48.000 [warn] Couldn't open "/Users/olgadegtiarova/Library/Application Support/Quiet/TorDataDirectory/state.tmp" (/Users/olgadegtiarova/Library/Application Support/Quiet/TorDataDirectory/state) for writing: No such file or directory
 waggle:tor Feb 24 11:34:48.000 [warn] Unable to write state to file "/Users/olgadegtiarova/Library/Application Support/Quiet/TorDataDirectory/state"; will try again later
 waggle:tor  +25s
 waggle:tor Feb 24 11:34:48.061 [notice] Tor 0.4.6.9 (git-ea2ada6d1459f829) running on Darwin with Libevent 2.1.11-stable, OpenSSL 1.1.1m, Zlib 1.2.11, Liblzma N/A, Libzstd N/A and Unknown N/A as libc.
 waggle:tor Feb 24 11:34:48.061 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
 waggle:tor Feb 24 11:34:48.062 [notice] Configuration file "/var/tmp/dist/tor/etc/tor/torrc" not present, using reasonable defaults.
 waggle:tor  +8ms
 waggle:tor Feb 24 11:34:48.063 [notice] Opening Socks listener on 127.0.0.1:52597
 waggle:tor  +2ms
 waggle:tor Feb 24 11:34:48.064 [notice] Opened Socks listener connection (ready) on 127.0.0.1:52597
 waggle:tor Feb 24 11:34:48.064 [notice] Opening HTTP tunnel listener on 127.0.0.1:52596
 waggle:tor Feb 24 11:34:48.064 [notice] Opened HTTP tunnel listener connection (ready) on 127.0.0.1:52596
 waggle:tor Feb 24 11:34:48.064 [notice] Opening Control listener on 127.0.0.1:52595
 waggle:tor Feb 24 11:34:48.064 [notice] Opened Control listener connection (ready) on 127.0.0.1:52595
 waggle:tor  +0ms
 waggle:tor Feb 24 11:34:48.000 [notice] Bootstrapped 0% (starting): Starting
 waggle:tor  +40ms
 waggle:tor Feb 24 11:34:48.000 [notice] Starting with guard context "default"
 waggle:tor  +1ms
 waggle:tor Feb 24 11:34:49.000 [notice] Bootstrapped 5% (conn): Connecting to a relay
 waggle:tor  +1s
 waggle:tor Feb 24 11:34:57.000 [notice] Bootstrapped 10% (conn_done): Connected to a relay
 waggle:tor  +8s
 waggle:tor Feb 24 11:35:10.000 [notice] Bootstrapped 14% (handshake): Handshaking with a relay
 waggle:tor  +13s
 waggle:tor Feb 24 11:35:28.000 [notice] Catching signal TERM, exiting cleanly.
 waggle:tor Feb 24 11:35:28.000 [warn] Couldn't open "/Users/olgadegtiarova/Library/Application Support/Quiet/TorDataDirectory/state.tmp" (/Users/olgadegtiarova/Library/Application Support/Quiet/TorDataDirectory/state) for writing: No such file or directory
 waggle:tor Feb 24 11:35:28.000 [warn] Unable to write state to file "/Users/olgadegtiarova/Library/Application Support/Quiet/TorDataDirectory/state"; will try again later
 waggle:tor  +18s
 waggle:tor Feb 24 11:35:28.080 [notice] Tor 0.4.6.9 (git-ea2ada6d1459f829) running on Darwin with Libevent 2.1.11-stable, OpenSSL 1.1.1m, Zlib 1.2.11, Liblzma N/A, Libzstd N/A and Unknown N/A as libc.
 waggle:tor Feb 24 11:35:28.080 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
 waggle:tor  +6ms
 waggle:tor Feb 24 11:35:28.080 [notice] Configuration file "/var/tmp/dist/tor/etc/tor/torrc" not present, using reasonable defaults.
 waggle:tor  +0ms
 waggle:tor Feb 24 11:35:28.082 [notice] Opening Socks listener on 127.0.0.1:52597
 waggle:tor  +2ms
 waggle:tor Feb 24 11:35:28.082 [notice] Opened Socks listener connection (ready) on 127.0.0.1:52597
 waggle:tor Feb 24 11:35:28.082 [notice] Opening HTTP tunnel listener on 127.0.0.1:52596
 waggle:tor Feb 24 11:35:28.082 [notice] Opened HTTP tunnel listener connection (ready) on 127.0.0.1:52596
 waggle:tor Feb 24 11:35:28.082 [notice] Opening Control listener on 127.0.0.1:52595
 waggle:tor Feb 24 11:35:28.082 [notice] Opened Control listener connection (ready) on 127.0.0.1:52595
 waggle:tor  +0ms
 waggle:tor Feb 24 11:35:28.000 [notice] Bootstrapped 0% (starting): Starting
 waggle:tor  +13ms
 waggle:tor Feb 24 11:35:28.000 [notice] Starting with guard context "default"
 waggle:tor  +1ms
 waggle:tor Feb 24 11:35:29.000 [notice] Bootstrapped 5% (conn): Connecting to a relay
 waggle:tor  +1s
Error: Failed to spawn tor 4 times
  at Tor.<anonymous> (/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/@quiet/waggle/lib/torManager/torManager.js:69:32)
  at Generator.next (<anonymous>)
  at /Applications/Quiet.app/Contents/Resources/app.asar/node_modules/@quiet/waggle/lib/torManager/torManager.js:27:71
  at new Promise (<anonymous>)
  at __awaiter (/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/@quiet/waggle/lib/torManager/torManager.js:23:12)
  at tryToSpawnTor (/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/@quiet/waggle/lib/torManager/torManager.js:67:45)
  at processTicksAndRejections (internal/process/task_queues.js:75:11)
 waggle:tor Feb 24 11:36:08.000 [notice] Catching signal TERM, exiting cleanly.
 waggle:tor  +39s
```

**Comment by kingalg** [comment]
Tor is failing someitnes crashing the app. I can't connect this to any specific event or action. It happened after a few restarts when the app was loading. After getting this error it's impossible to use the app.

**Comment by vinkabuki** [comment]
This is not about "Unable to write state to file" - it's after we force kill tor. It's about timeout. It happens sometimes that it takes a lot of time for tor to start. I've found out that sometimes deleting tor data may help, it doesn't affect the app in any way - it's tor internals for establishing circuits.

**Comment by EmiM** [comment]
We are already cleaning tor data before restarting tor

**Comment by EmiM** [comment]
https://github.com/ZbayApp/monorepo/pull/291 increased tor timeout on our side (to the default tor's timeout -> 120 seconds) and number of tries of restarting tor.
