### ISSUE TITLE
Tor fails to spawn sometimes because of "Bug: Acting on config options left us in a broken state."

### ISSUE THREAD

**Issue by EmiM** [ZbayApp/monorepo#278]
OS: Windows 10
Quiet app version: 0.3.0-alpha.7

```
2022-02-25T12:18:30.216Z waggle:socket Data server running on port 49776
2022-02-25T12:18:30.221Z waggle:conn Creating https proxy agent: 49773
2022-02-25T12:18:30.225Z waggle:conn Initialized socket listeners
2022-02-25T12:18:30.227Z waggle:tor Initializing tor...
2022-02-25T12:18:30.615Z waggle:tor Feb 25 13:18:30.620 [notice] Tor 0.4.6.9 (git-ea2ada6d1459f829) running on Windows 8 [or later] with Libevent 2.1.11-stable, OpenSSL 1.1.1h, Zlib 1.2.11, Liblzma N/A, Libzstd N/A and Unknown N/A as libc.
Feb 25 13:18:30.620 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
2022-02-25T12:18:30.679Z waggle:tor Feb 25 13:18:30.686 [notice] Configuration file "C:\Users\kinga\AppData\Roaming\tor\torrc" not present, using reasonable defaults.
2022-02-25T12:18:30.684Z waggle:tor Feb 25 13:18:30.690 [warn] Path for GeoIPFile (<default>) is relative and will resolve to C:\Users\kinga\<default>. Is this what you wanted?
Feb 25 13:18:30.690 [warn] Path for GeoIPv6File (<default>) is relative and will resolve to C:\Users\kinga\<default>. Is this what you wanted?
2022-02-25T12:18:30.691Z waggle:tor Feb 25 13:18:30.698 [notice] Opening Socks listener on 127.0.0.1:49774
Feb 25 13:18:30.698 [notice] Opened Socks listener connection (ready) on 127.0.0.1:49774
Feb 25 13:18:30.698 [notice] Opening HTTP tunnel listener on 127.0.0.1:49773
2022-02-25T12:18:30.693Z waggle:tor Feb 25 13:18:30.698 [notice] Opened HTTP tunnel listener connection (ready) on 127.0.0.1:49773
Feb 25 13:18:30.699 [notice] Opening Control listener on 127.0.0.1:49772
Feb 25 13:18:30.699 [notice] Opened Control listener connection (ready) on 127.0.0.1:49772
2022-02-25T12:18:30.696Z waggle:tor Feb 25 13:18:30.000 [warn] It looks like another Tor process is running with the same data directory.  Waiting 5 seconds to see if it goes away.
2022-02-25T12:18:35.709Z waggle:tor Feb 25 13:18:35.000 [err] No, it's still there.  Exiting.
Feb 25 13:18:35.000 [err] set_options(): Bug: Acting on config options left us in a broken state. Dying. (on Tor 0.4.6.9 ea2ada6d1459f829)
2022-02-25T12:18:35.711Z waggle:tor Feb 25 13:18:35.000 [err] Reading config failed--see warnings above.
2022-02-25T12:19:10.660Z waggle:tor Feb 25 13:19:10.658 [notice] Tor 0.4.6.9 (git-ea2ada6d1459f829) running on Windows 8 [or later] with Libevent 2.1.11-stable, OpenSSL 1.1.1h, Zlib 1.2.11, Liblzma N/A, Libzstd N/A and Unknown N/A as libc.
Feb 25 13:19:10.658 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
2022-02-25T12:19:10.729Z waggle:tor Feb 25 13:19:10.729 [notice] Configuration file "C:\Users\kinga\AppData\Roaming\tor\torrc" not present, using reasonable defaults.
2022-02-25T12:19:10.739Z waggle:tor Feb 25 13:19:10.739 [warn] Path for GeoIPFile (<default>) is relative and will resolve to C:\Users\kinga\<default>. Is this what you wanted?
Feb 25 13:19:10.739 [warn] Path for GeoIPv6File (<default>) is relative and will resolve to C:\Users\kinga\<default>. Is this what you wanted?
2022-02-25T12:19:10.748Z waggle:tor Feb 25 13:19:10.747 [notice] Opening Socks listener on 127.0.0.1:49774
Feb 25 13:19:10.748 [notice] Opened Socks listener connection (ready) on 127.0.0.1:49774
Feb 25 13:19:10.748 [notice] Opening HTTP tunnel listener on 127.0.0.1:49773
2022-02-25T12:19:10.749Z waggle:tor Feb 25 13:19:10.748 [notice] Opened HTTP tunnel listener connection (ready) on 127.0.0.1:49773
Feb 25 13:19:10.748 [notice] Opening Control listener on 127.0.0.1:49772
Feb 25 13:19:10.748 [notice] Opened Control listener connection (ready) on 127.0.0.1:49772
2022-02-25T12:19:10.759Z waggle:tor Feb 25 13:19:10.000 [warn] It looks like another Tor process is running with the same data directory.  Waiting 5 seconds to see if it goes away.
2022-02-25T12:19:15.764Z waggle:tor Feb 25 13:19:15.000 [err] No, it's still there.  Exiting.
Feb 25 13:19:15.000 [err] set_options(): Bug: Acting on config options left us in a broken state. Dying. (on Tor 0.4.6.9 ea2ada6d1459f829)
2022-02-25T12:19:15.766Z waggle:tor Feb 25 13:19:15.000 [err] Reading config failed--see warnings above.
2022-02-25T12:19:50.687Z waggle:tor Feb 25 13:19:50.686 [notice] Tor 0.4.6.9 (git-ea2ada6d1459f829) running on Windows 8 [or later] with Libevent 2.1.11-stable, OpenSSL 1.1.1h, Zlib 1.2.11, Liblzma N/A, Libzstd N/A and Unknown N/A as libc.
Feb 25 13:19:50.686 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
2022-02-25T12:19:50.757Z waggle:tor Feb 25 13:19:50.757 [notice] Configuration file "C:\Users\kinga\AppData\Roaming\tor\torrc" not present, using reasonable defaults.
2022-02-25T12:19:50.762Z waggle:tor Feb 25 13:19:50.761 [warn] Path for GeoIPFile (<default>) is relative and will resolve to C:\Users\kinga\<default>. Is this what you wanted?
Feb 25 13:19:50.761 [warn] Path for GeoIPv6File (<default>) is relative and will resolve to C:\Users\kinga\<default>. Is this what you wanted?
2022-02-25T12:19:50.775Z waggle:tor Feb 25 13:19:50.774 [notice] Opening Socks listener on 127.0.0.1:49774
Feb 25 13:19:50.775 [notice] Opened Socks listener connection (ready) on 127.0.0.1:49774
Feb 25 13:19:50.775 [notice] Opening HTTP tunnel listener on 127.0.0.1:49773
2022-02-25T12:19:50.776Z waggle:tor Feb 25 13:19:50.775 [notice] Opened HTTP tunnel listener connection (ready) on 127.0.0.1:49773
Feb 25 13:19:50.775 [notice] Opening Control listener on 127.0.0.1:49772
Feb 25 13:19:50.775 [notice] Opened Control listener connection (ready) on 127.0.0.1:49772
2022-02-25T12:19:50.778Z waggle:tor Feb 25 13:19:50.000 [warn] It looks like another Tor process is running with the same data directory.  Waiting 5 seconds to see if it goes away.
2022-02-25T12:19:55.795Z waggle:tor Feb 25 13:19:55.000 [err] No, it's still there.  Exiting.
Feb 25 13:19:55.000 [err] set_options(): Bug: Acting on config options left us in a broken state. Dying. (on Tor 0.4.6.9 ea2ada6d1459f829)
Feb 25 13:19:55.000 [err] Reading config failed--see warnings above.
2022-02-25T12:20:30.711Z waggle:tor Feb 25 13:20:30.710 [notice] Tor 0.4.6.9 (git-ea2ada6d1459f829) running on Windows 8 [or later] with Libevent 2.1.11-stable, OpenSSL 1.1.1h, Zlib 1.2.11, Liblzma N/A, Libzstd N/A and Unknown N/A as libc.
Feb 25 13:20:30.710 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
2022-02-25T12:20:30.786Z waggle:tor Feb 25 13:20:30.785 [notice] Configuration file "C:\Users\kinga\AppData\Roaming\tor\torrc" not present, using reasonable defaults.
2022-02-25T12:20:30.792Z waggle:tor Feb 25 13:20:30.790 [warn] Path for GeoIPFile (<default>) is relative and will resolve to C:\Users\kinga\<default>. Is this what you wanted?
Feb 25 13:20:30.790 [warn] Path for GeoIPv6File (<default>) is relative and will resolve to C:\Users\kinga\<default>. Is this what you wanted?
2022-02-25T12:20:30.804Z waggle:tor Feb 25 13:20:30.803 [notice] Opening Socks listener on 127.0.0.1:49774
Feb 25 13:20:30.803 [notice] Opened Socks listener connection (ready) on 127.0.0.1:49774
Feb 25 13:20:30.803 [notice] Opening HTTP tunnel listener on 127.0.0.1:49773
2022-02-25T12:20:30.806Z waggle:tor Feb 25 13:20:30.804 [notice] Opened HTTP tunnel listener connection (ready) on 127.0.0.1:49773
Feb 25 13:20:30.804 [notice] Opening Control listener on 127.0.0.1:49772
Feb 25 13:20:30.804 [notice] Opened Control listener connection (ready) on 127.0.0.1:49772
2022-02-25T12:20:30.808Z waggle:tor Feb 25 13:20:30.000 [warn] It looks like another Tor process is running with the same data directory.  Waiting 5 seconds to see if it goes away.
2022-02-25T12:20:35.817Z waggle:tor Feb 25 13:20:35.000 [err] No, it's still there.  Exiting.
Feb 25 13:20:35.000 [err] set_options(): Bug: Acting on config options left us in a broken state. Dying. (on Tor 0.4.6.9 ea2ada6d1459f829)
Feb 25 13:20:35.000 [err] Reading config failed--see warnings above.
Error: Failed to spawn tor 4 times
    at Tor.<anonymous> (C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\node_modules\@quiet\waggle\lib\torManager\torManager.js:69:32)
    at Generator.next (<anonymous>)
    at C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\node_modules\@quiet\waggle\lib\torManager\torManager.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\node_modules\@quiet\waggle\lib\torManager\torManager.js:23:12)
    at tryToSpawnTor (C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\node_modules\@quiet\waggle\lib\torManager\torManager.js:67:45)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

**Comment by kingalg** [comment]
It happened after a few restarts. First time I saw it when I closed Quiet when the app wa still loading and then restarted it. Restarting app doesn't help to get rid of this error. App needs to be reinstalled to be in usable state again.

**Comment by vinkabuki** [comment]
meta solution to hanging tor process on windows:
Investigate if windows defender or other agent is not denying access to kill the old process
If for some edge case reason it's still there, we can catch "tor process is running" log, check in what directory it's working and if that meets our criteria, kill it

**Comment by EmiM** [comment]
https://github.com/ZbayApp/monorepo/pull/291
Added extra mechanism that clears hanging tor - for the edge case where there is no torPid file (which we usually use to clear old tor) but tor process exists.

**Comment by kingalg** [comment]
Version: 0.4.0-alpha.3

I did not encounter this problem in this version.
