### ISSUE TITLE
Sending message to minimized Quiet on Windows crashes the app

### ISSUE THREAD

**Issue by kingalg** [ZbayApp/monorepo#404]
Version: 0.4.1-alpha.1
Last version on which I'm sure that this was working: 0.4.0-alpha.3

Sending message to minimized Quiet on Windows crashes the app (it's impossible to send or receive any message)

Steps to recreate:
1) have one Quiet installed on Windows and second one on any other system
2) minimize Quiet on Windows
3) send any message to the community that Quiet on Windows is a part of

Expected behaviour - Quiet on Windows get notification (according to what has been set up in Settings), user can see a new message and can continue using app as always

What happen - no notification is received, message is not delivered any later tries of sending or receiving messages is blocked until the app is restarted (restarting the app fixes the issue)

Logs from crashed app:
Microsoft Windows [Version 10.0.19043.1586]
(c) Microsoft Corporation. Wszelkie prawa zastrzeżone.

C:\Users\kinga>set DEBUG=waggle*,nectar*,quiet*,frontend*

C:\Users\kinga>C:\Users\kinga\AppData\Local\Programs\quiet\Quiet.exe

C:\Users\kinga>
Read extra envs: { TEST_MODE: 'false' }
2022-03-29T10:03:38.424Z quiet Initializing debug logger
2022-03-29T10:03:38.446Z quiet Initializing debug logger
2022-03-29T10:03:38.548Z quiet Initializing debug logger
2022-03-29T10:03:39.091Z quiet Initializing debug logger
2022-03-29T10:03:39.244Z quiet Initializing debug logger
2022-03-29T10:03:39.247Z quiet Initializing debug logger
2022-03-29T10:03:39.581Z quiet Initializing debug logger
2022-03-29T10:03:43.130Z quiet Initializing debug logger
2022-03-29T10:03:43.131Z quiet Initializing debug logger
2022-03-29T10:03:43.135Z quiet Initializing debug logger
2022-03-29T10:03:43.144Z quiet Initializing debug logger
2022-03-29T10:03:47.664Z quiet Initializing debug logger
2022-03-29T10:03:47.679Z quiet Initializing debug logger
2022-03-29T10:03:48.245Z quiet Initializing debug logger

2022-03-29T10:03:48.661Z frontend:main:main created windows
2022-03-29T10:04:03.764Z waggle:socket Data server running on port 51073
2022-03-29T10:04:03.766Z waggle:conn Creating https proxy agent: 51070
2022-03-29T10:04:03.772Z waggle:conn Initialized socket listeners
2022-03-29T10:04:03.776Z waggle:tor Initializing tor...
2022-03-29T10:04:04.155Z waggle:tor C:\Users\kinga\AppData\Roaming\Quiet\torPid.json exists. Old tor pid: 7900
2022-03-29T10:04:04.157Z waggle:tor Trying to spawn tor for the 0 time...
2022-03-29T10:04:05.839Z waggle:tor Deleting C:\Users\kinga\AppData\Roaming\Quiet\torPid.json
2022-03-29T10:04:05.946Z waggle:tor Mar 29 12:04:05.945 [notice] Tor 0.4.6.9 (git-ea2ada6d1459f829) running on Windows 8 [or later] with Libevent 2.1.11-stable, OpenSSL 1.1.1h, Zlib 1.2.11, Liblzma N/A, Libzstd N/A and Unknown N/A as libc.
Mar 29 12:04:05.945 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning

2022-03-29T10:04:06.040Z waggle:tor Mar 29 12:04:06.038 [notice] Configuration file "C:\Users\kinga\AppData\Roaming\tor\torrc" not present, using reasonable defaults.

2022-03-29T10:04:06.047Z waggle:tor Mar 29 12:04:06.046 [warn] Path for GeoIPFile (<default>) is relative and will resolve to C:\Users\kinga\<default>. Is this what you wanted?
Mar 29 12:04:06.046 [warn] Path for GeoIPv6File (<default>) is relative and will resolve to C:\Users\kinga\<default>. Is this what you wanted?

2022-03-29T10:04:06.060Z waggle:tor Mar 29 12:04:06.059 [notice] Opening Socks listener on 127.0.0.1:51071
Mar 29 12:04:06.059 [notice] Opened Socks listener connection (ready) on 127.0.0.1:51071

2022-03-29T10:04:06.062Z waggle:tor Mar 29 12:04:06.059 [notice] Opening HTTP tunnel listener on 127.0.0.1:51070
Mar 29 12:04:06.059 [notice] Opened HTTP tunnel listener connection (ready) on 127.0.0.1:51070
Mar 29 12:04:06.060 [notice] Opening Control listener on 127.0.0.1:51069
Mar 29 12:04:06.060 [notice] Opened Control listener connection (ready) on 127.0.0.1:51069

2022-03-29T10:04:06.221Z waggle:tor Mar 29 12:04:06.000 [notice] Bootstrapped 0% (starting): Starting

Checking for update
Update for version 0.4.1-alpha.1 is not available (latest version: 0.4.1-alpha.1, downgrade is disallowed).
Checking for update
2022-03-29T10:04:10.893Z frontend:main:main checking for updates...
Update for version 0.4.1-alpha.1 is not available (latest version: 0.4.1-alpha.1, downgrade is disallowed).
2022-03-29T10:04:11.098Z frontend:main:main event no update
2022-03-29T10:04:18.318Z waggle:tor Mar 29 12:04:18.000 [notice] Starting with guard context "default"

2022-03-29T10:04:19.463Z waggle:tor Mar 29 12:04:19.000 [notice] Bootstrapped 5% (conn): Connecting to a relay

2022-03-29T10:04:19.555Z waggle:tor Mar 29 12:04:19.000 [notice] Bootstrapped 10% (conn_done): Connected to a relay

2022-03-29T10:04:19.606Z waggle:tor Mar 29 12:04:19.000 [notice] Bootstrapped 14% (handshake): Handshaking with a relay

2022-03-29T10:04:19.728Z waggle:tor Mar 29 12:04:19.000 [notice] Bootstrapped 15% (handshake_done): Handshake with a relay done
Mar 29 12:04:19.000 [notice] Bootstrapped 75% (enough_dirinfo): Loaded enough directory info to build circuits
Mar 29 12:04:19.000 [notice] Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits
Mar 29 12:04:19.000 [notice] Bootstrapped 95% (circuit_create): Establishing a Tor circuit

2022-03-29T10:04:19.907Z waggle:tor Mar 29 12:04:19.000 [notice] Bootstrapped 100% (done): Done

2022-03-29T10:04:19.908Z waggle:conn Spawned Tor
2022-03-29T10:04:20.061Z waggle:socket websocket connected
2022-03-29T10:04:20.152Z waggle:socket Launching community 28795F54382E05CA1C6FDC69F3C0FDD0 for QmXs3HwFk2FM9AtRy8HSvHdUSZNSuLrXjbc9CbzeNFwKdn
2022-03-29T10:04:20.184Z waggle:communities Spawning hidden service for community 28795F54382E05CA1C6FDC69F3C0FDD0, peer: QmXs3HwFk2FM9AtRy8HSvHdUSZNSuLrXjbc9CbzeNFwKdn
2022-03-29T10:04:20.224Z waggle:tor Mar 29 12:04:20.000 [notice] New control connection opened from 127.0.0.1.

2022-03-29T10:04:20.817Z waggle:communities Launching community 28795F54382E05CA1C6FDC69F3C0FDD0, peer: QmXs3HwFk2FM9AtRy8HSvHdUSZNSuLrXjbc9CbzeNFwKdn
2022-03-29T10:04:20.897Z waggle:communities Initializing storage for peer QmXs3HwFk2FM9AtRy8HSvHdUSZNSuLrXjbc9CbzeNFwKdn...
2022-03-29T10:04:20.899Z waggle:conn Initializing libp2p for QmXs3HwFk2FM9AtRy8HSvHdUSZNSuLrXjbc9CbzeNFwKdn
2022-03-29T10:04:20.988Z waggle:conn Initialized libp2p for peer QmXs3HwFk2FM9AtRy8HSvHdUSZNSuLrXjbc9CbzeNFwKdn
2022-03-29T10:04:20.988Z waggle:conn Creating storage for community: 28795F54382E05CA1C6FDC69F3C0FDD0
2022-03-29T10:04:20.994Z waggle:db STORAGE: Entered init
2022-03-29T10:04:20.998Z waggle:db Initializing IPFS
2022-03-29T10:04:21.518Z waggle:conn QmXs3HwFk2FM9AtRy8HSvHdUSZNSuLrXjbc9CbzeNFwKdn discovered QmTq14Dq989GrGLve8CTTB3jmpwpkiz7znjabZc3gKLiRf
2022-03-29T10:04:21.737Z waggle:db 1/6
2022-03-29T10:04:21.738Z waggle:db createDbForChannels init
2022-03-29T10:04:21.852Z waggle:db ALL CHANNELS COUNT: 1
2022-03-29T10:04:21.854Z waggle:db ALL CHANNELS COUNT: [ 'general' ]
2022-03-29T10:04:21.860Z waggle:db STORAGE: Finished createDbForChannels
2022-03-29T10:04:21.863Z waggle:db 2/6
2022-03-29T10:04:21.865Z waggle:db createDbForCertificates init
2022-03-29T10:04:21.940Z waggle:db Loaded certificates to memory
2022-03-29T10:04:21.942Z waggle:io Sending 2 certificates
2022-03-29T10:04:21.950Z waggle:db ALL Certificates COUNT: 2
2022-03-29T10:04:21.952Z waggle:db ALL Certificates: [
  'MIICFjCCAb0CBgF/0h4TejAKBggqhkjOPQQDAjAXMRUwEwYDVQQDEwxtYWMyODAzMjJjb20wHhcNMjIwMzI4MjAwMTAwWhcNMzAwMTMxMjMwMDAwWjBJMUcwRQYDVQQDEz5zdnhqZWg0cDZvd3lpdWhtZXdtMnAyY2huM2M0a3RqbWRpZnNneHZqaXp1Yno0aGFycHZneWx5ZC5vbmlvbjBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABBO2BI56rlxgZffgbpT/4wp9v/hJfPV06VBhiJE3s7rDcRuc3alrkEpHPelGY43WJKeD39wsn6eZY5MbNb1LkJCjgccwgcQwCQYDVR0TBAIwADALBgNVHQ8EBAMCAI4wHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMC8GCSqGSIb3DQEJDAQiBCB7pmaVzMt81tpDKFyScSbOJoldhYHtXVxojMnfd1DfEzAbBgorBgEEAYOMGwIBBA0TC21hYzI4MDMyMnVzMD0GCSsGAQIBDwMBAQQwEy5RbVRxMTREcTk4OUdyR0x2ZThDVFRCM2ptcHdwa2l6N3puamFiWmMzZ0tMaVJmMAoGCCqGSM49BAMCA0cAMEQCIDgghaKspIYhJ6+dZgdEsoepa1jwloqJ9q39ghroeAsPAiAESel05Ky5o+ipC93l0KIqIcsvjc9MdHj5F3neoOSbng==',
  'MIICFjCCAb0CBgF/1L2gyjAKBggqhkjOPQQDAjAXMRUwEwYDVQQDEwxtYWMyODAzMjJjb20wHhcNMjIwMzI5MDgxNDMxWhcNMzAwMTMxMjMwMDAwWjBJMUcwRQYDVQQDEz5xdDNjNnJ4bmZoMjc3NmQ0YzQ1a2xhamFxbm15d3V2anNiNXhwaHo3dHVieHpidmwydWpuNzNpZC5vbmlvbjBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABHm576w0EYoAVQQsCUH6UTxTAARNzr8agQMNcyRotHNmHK3c0UGLjRNJYZOmJwJTblctV4dQdqDK/Jv+LTjCO4ajgccwgcQwCQYDVR0TBAIwADALBgNVHQ8EBAMCAI4wHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMC8GCSqGSIb3DQEJDAQiBCCo5lSjakc4R6uGElDUR7UWQVyJCo85Vm+JfYXZcdQkxjAbBgorBgEEAYOMGwIBBA0TC3dpbjI4MDMyMnVzMD0GCSsGAQIBDwMBAQQwEy5RbVhzM0h3RmsyRk05QXRSeThIU3ZIZFVTWk5TdUxyWGpiYzlDYnplTkZ3S2RuMAoGCCqGSM49BAMCA0cAMEQCICVqBKvXf/gwAKUqiyvn3mgzMsfbk/fLEHTNW9RQv1EfAiAj0KlbCaNtiRqFKFH5g3nVe9FTEjlAqhKYTcHNyB/IrQ=='
]
2022-03-29T10:04:21.955Z waggle:db STORAGE: Finished createDbForCertificates
2022-03-29T10:04:21.959Z waggle:db 3/6
2022-03-29T10:04:22.018Z waggle:db ALL MESSAGE THREADS COUNT: 0
2022-03-29T10:04:22.019Z waggle:db 4/6
2022-03-29T10:04:22.493Z waggle:db Subscribing to channel  general
2022-03-29T10:04:22.493Z waggle:db 5/6
2022-03-29T10:04:22.499Z waggle:db 6/6
2022-03-29T10:04:22.503Z waggle:communities Initialized storage for peer QmXs3HwFk2FM9AtRy8HSvHdUSZNSuLrXjbc9CbzeNFwKdn
2022-03-29T10:04:22.506Z waggle:io Launched community 28795F54382E05CA1C6FDC69F3C0FDD0
2022-03-29T10:04:28.281Z waggle:conn QmXs3HwFk2FM9AtRy8HSvHdUSZNSuLrXjbc9CbzeNFwKdn connected to QmTq14Dq989GrGLve8CTTB3jmpwpkiz7znjabZc3gKLiRf
2022-03-29T10:04:34.660Z waggle:conn QmXs3HwFk2FM9AtRy8HSvHdUSZNSuLrXjbc9CbzeNFwKdn connected to QmTq14Dq989GrGLve8CTTB3jmpwpkiz7znjabZc3gKLiRf
2022-03-29T10:10:47.219Z waggle:db REPLICATED: Certificates
2022-03-29T10:10:47.221Z waggle:io Sending 3 certificates
2022-03-29T10:11:02.300Z waggle:conn QmXs3HwFk2FM9AtRy8HSvHdUSZNSuLrXjbc9CbzeNFwKdn discovered QmZZqPfKW2nqwGM8KYkCfpfTGCiwe39XunVduKRNvbvkuB
2022-03-29T10:11:03.765Z waggle:conn QmXs3HwFk2FM9AtRy8HSvHdUSZNSuLrXjbc9CbzeNFwKdn connected to QmZZqPfKW2nqwGM8KYkCfpfTGCiwe39XunVduKRNvbvkuB
2022-03-29T10:11:11.464Z waggle:conn QmXs3HwFk2FM9AtRy8HSvHdUSZNSuLrXjbc9CbzeNFwKdn connected to QmZZqPfKW2nqwGM8KYkCfpfTGCiwe39XunVduKRNvbvkuB
2022-03-29T10:11:36.843Z waggle:db progress 33/33. Address: /orbitdb/zdpuAzeS7hf4tDBvWNvELHi7vC4TzwZzLp32a1XJSubR9vuKV/channels.general
2022-03-29T10:11:36.844Z waggle:db progress 33/33. Address: /orbitdb/zdpuAzeS7hf4tDBvWNvELHi7vC4TzwZzLp32a1XJSubR9vuKV/channels.general
2022-03-29T10:11:36.848Z waggle:io Emitting message
2022-03-29T10:11:48.644Z waggle:db progress 34/34. Address: /orbitdb/zdpuAzeS7hf4tDBvWNvELHi7vC4TzwZzLp32a1XJSubR9vuKV/channels.general
2022-03-29T10:11:48.644Z waggle:db progress 34/34. Address: /orbitdb/zdpuAzeS7hf4tDBvWNvELHi7vC4TzwZzLp32a1XJSubR9vuKV/channels.general
2022-03-29T10:11:48.650Z waggle:io Emitting message
2022-03-29T10:11:49.854Z waggle:db progress 35/35. Address: /orbitdb/zdpuAzeS7hf4tDBvWNvELHi7vC4TzwZzLp32a1XJSubR9vuKV/channels.general
2022-03-29T10:11:49.854Z waggle:db progress 35/35. Address: /orbitdb/zdpuAzeS7hf4tDBvWNvELHi7vC4TzwZzLp32a1XJSubR9vuKV/channels.general
2022-03-29T10:11:49.858Z waggle:io Emitting message
Checking for update
2022-03-29T10:49:58.661Z frontend:main:main checking for updates...
2022-03-29T10:50:02.022Z waggle:conn QmXs3HwFk2FM9AtRy8HSvHdUSZNSuLrXjbc9CbzeNFwKdn disconnected from QmTq14Dq989GrGLve8CTTB3jmpwpkiz7znjabZc3gKLiRf
2022-03-29T10:50:02.067Z waggle:conn QmXs3HwFk2FM9AtRy8HSvHdUSZNSuLrXjbc9CbzeNFwKdn disconnected from QmZZqPfKW2nqwGM8KYkCfpfTGCiwe39XunVduKRNvbvkuB
Error: Error: net::ERR_NETWORK_IO_SUSPENDED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:7068)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
From previous event:
    at GenericProvider.getLatestVersion (C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\node_modules\electron-updater\src\providers\GenericProvider.ts:18:25)
    at C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:347:26
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at NsisUpdater.getUpdateInfoAndProvider (C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:336:43)
    at C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:363:31
    at Generator.next (<anonymous>)
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:360:34)
    at NsisUpdater.checkForUpdates (C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:220:35)
    at C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\dist\main\main.js:236:46
    at Generator.next (<anonymous>)
    at C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\dist\main\main.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\dist\main\main.js:4:12)
    at checkForUpdate (C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\dist\main\main.js:202:33)
    at C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\dist\main\main.js:292:50
    at Generator.next (<anonymous>)
    at C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\dist\main\main.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\dist\main\main.js:4:12)
    at Timeout._onTimeout (C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\dist\main\main.js:288:31)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
2022-03-29T10:50:02.686Z frontend:main:main Error: net::ERR_NETWORK_IO_SUSPENDED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:7068)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
From previous event:
    at GenericProvider.getLatestVersion (C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\node_modules\electron-updater\src\providers\GenericProvider.ts:18:25)
    at C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:347:26
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at NsisUpdater.getUpdateInfoAndProvider (C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:336:43)
    at C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:363:31
    at Generator.next (<anonymous>)
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:360:34)
    at NsisUpdater.checkForUpdates (C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:220:35)
    at C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\dist\main\main.js:236:46
    at Generator.next (<anonymous>)
    at C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\dist\main\main.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\dist\main\main.js:4:12)
    at checkForUpdate (C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\dist\main\main.js:202:33)
    at C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\dist\main\main.js:292:50
    at Generator.next (<anonymous>)
    at C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\dist\main\main.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\dist\main\main.js:4:12)
    at Timeout._onTimeout (C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\dist\main\main.js:288:31)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
2022-03-29T10:50:02.884Z frontend:main:main:err Unknown Error
2022-03-29T10:50:03.021Z frontend:main:main:err Error: net::ERR_NETWORK_IO_SUSPENDED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:7068)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
From previous event:
    at GenericProvider.getLatestVersion (C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\node_modules\electron-updater\src\providers\GenericProvider.ts:18:25)
    at C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:347:26
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at NsisUpdater.getUpdateInfoAndProvider (C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:336:43)
    at C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:363:31
    at Generator.next (<anonymous>)
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:360:34)
    at NsisUpdater.checkForUpdates (C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:220:35)
    at C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\dist\main\main.js:236:46
    at Generator.next (<anonymous>)
    at C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\dist\main\main.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\dist\main\main.js:4:12)
    at checkForUpdate (C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\dist\main\main.js:202:33)
    at C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\dist\main\main.js:292:50
    at Generator.next (<anonymous>)
    at C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\dist\main\main.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\dist\main\main.js:4:12)
    at Timeout._onTimeout (C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\dist\main\main.js:288:31)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
2022-03-29T10:50:18.041Z waggle:socket websocket connected
2022-03-29T10:50:21.638Z waggle:conn QmXs3HwFk2FM9AtRy8HSvHdUSZNSuLrXjbc9CbzeNFwKdn connected to QmZZqPfKW2nqwGM8KYkCfpfTGCiwe39XunVduKRNvbvkuB
2022-03-29T10:50:25.395Z waggle:conn QmXs3HwFk2FM9AtRy8HSvHdUSZNSuLrXjbc9CbzeNFwKdn connected to QmTq14Dq989GrGLve8CTTB3jmpwpkiz7znjabZc3gKLiRf
Checking for update
2022-03-29T11:04:57.754Z frontend:main:main checking for updates...
Update for version 0.4.1-alpha.1 is not available (latest version: 0.4.1-alpha.1, downgrade is disallowed).
2022-03-29T11:04:58.569Z frontend:main:main event no update
2022-03-29T11:17:57.812Z waggle:conn QmXs3HwFk2FM9AtRy8HSvHdUSZNSuLrXjbc9CbzeNFwKdn disconnected from QmZZqPfKW2nqwGM8KYkCfpfTGCiwe39XunVduKRNvbvkuB

Logs from app from which message has been send:
Microsoft Windows [Version 10.0.19043.1586]
(c) Microsoft Corporation. Wszelkie prawa zastrzeżone.

C:\Users\kinga>set DATA_DIR=quiet2

C:\Users\kinga>C:\Users\kinga\AppData\Local\Programs\quiet\Quiet.exe

C:\Users\kinga>
Read extra envs: { TEST_MODE: 'false' }

Checking for update
Generated new staging user ID: fa2b2f92-4d18-577a-8904-dc13b4f16291
Update for version 0.4.1-alpha.1 is not available (latest version: 0.4.1-alpha.1, downgrade is disallowed).
Checking for update
Update for version 0.4.1-alpha.1 is not available (latest version: 0.4.1-alpha.1, downgrade is disallowed).
to get started, enter:

        jsipfs cat /ipfs/QmRaaUwTNfwgFZpeUy8qrZwrp2dY4kCKmmB5xEqvH3vtD1/readme

Checking for update
Error: Error: net::ERR_NETWORK_IO_SUSPENDED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:7068)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
From previous event:
    at GenericProvider.getLatestVersion (C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\node_modules\electron-updater\src\providers\GenericProvider.ts:18:25)
    at C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:347:26
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at NsisUpdater.getUpdateInfoAndProvider (C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:336:43)
    at C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:363:31
    at Generator.next (<anonymous>)
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:360:34)
    at NsisUpdater.checkForUpdates (C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:220:35)
    at C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\dist\main\main.js:236:46
    at Generator.next (<anonymous>)
    at C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\dist\main\main.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\dist\main\main.js:4:12)
    at checkForUpdate (C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\dist\main\main.js:202:33)
    at C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\dist\main\main.js:292:50
    at Generator.next (<anonymous>)
    at C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\dist\main\main.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\dist\main\main.js:4:12)
    at Timeout._onTimeout (C:\Users\kinga\AppData\Local\Programs\quiet\resources\app.asar\dist\main\main.js:288:31)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
Checking for update
Update for version 0.4.1-alpha.1 is not available (latest version: 0.4.1-alpha.1, downgrade is disallowed).

**Comment by kingalg** [comment]
Version 0.4.1-alpha.5

Fixed.
