### ISSUE TITLE
Problem with downloading chromium on CI - makes pipeline fail (hides failed tests)

### ISSUE THREAD

**Issue by EmiM** [ZbayApp/monorepo#436]
https://github.com/ZbayApp/monorepo/runs/5988639342?check_suite_focus=true

```
npm ERR! npm WARN cleanup Failed to remove some directories [
npm ERR! npm WARN cleanup   [
npm ERR! npm WARN cleanup     '/Users/runner/.npm/_cacache/tmp/git-clone6IC9gT/node_modules/ipfs-daemon',
npm ERR! npm WARN cleanup     [Error: EINVAL: invalid argument, rmdir '/Users/runner/.npm/_cacache/tmp/git-clone6IC9gT/node_modules/ipfs-daemon/node_modules/ipfs-http-client/cjs/src/pin/remote'] {
npm ERR! npm WARN cleanup       errno: -22,
npm ERR! npm WARN cleanup       code: 'EINVAL',
npm ERR! npm WARN cleanup       syscall: 'rmdir',
npm ERR! npm WARN cleanup       path: '/Users/runner/.npm/_cacache/tmp/git-clone6IC9gT/node_modules/ipfs-daemon/node_modules/ipfs-http-client/cjs/src/pin/remote'
npm ERR! npm WARN cleanup     }
npm ERR! npm WARN cleanup   ]
npm ERR! npm WARN cleanup ]
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path /Users/runner/.npm/_cacache/tmp/git-clone6IC9gT/node_modules/chromium
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c node install.js
npm ERR! npm ERR! Step 1. Retrieving Chromium revision number
npm ERR! npm ERR! Step 2. Downloading Chromium revision 991444
npm ERR! npm ERR! /Users/runner/.npm/_cacache/tmp/git-clone6IC9gT/node_modules/p-cancelable/index.js:48
npm ERR! npm ERR! 					throw new Error('The `onCancel` handler was attached after the promise settled.');
npm ERR! npm ERR! 					      ^
npm ERR! npm ERR! 
npm ERR! npm ERR! Error: The `onCancel` handler was attached after the promise settled.
npm ERR! npm ERR!     at onCancel (/Users/runner/.npm/_cacache/tmp/git-clone6IC9gT/node_modules/p-cancelable/index.js:48:12)
npm ERR! npm ERR!     at makeRequest (/Users/runner/.npm/_cacache/tmp/git-clone6IC9gT/node_modules/got/dist/source/as-promise/index.js:38:13)
npm ERR! npm ERR!     at Request.<anonymous> (/Users/runner/.npm/_cacache/tmp/git-clone6IC9gT/node_modules/got/dist/source/as-promise/index.js:143:17)
npm ERR! npm ERR!     at Object.onceWrapper (node:events:646:26)
npm ERR! npm ERR!     at Request.emit (node:events:526:28)
npm ERR! npm ERR!     at Timeout.retry (/Users/runner/.npm/_cacache/tmp/git-clone6IC9gT/node_modules/got/dist/source/core/index.js:1270:30)
npm ERR! npm ERR!     at listOnTimeout (node:internal/timers:559:17)
npm ERR! npm ERR!     at processTimers (node:internal/timers:502:7)
```

**Comment by siepra** [comment]
Related PR https://github.com/ZbayApp/monorepo/pull/451
